#!/usr/bin/env lua

-- generate.lua <input.sql> [output.lua]
-- Reads annotated SQL file and writes a Lua module.

require("utils")

local function trim(s)
  return s:match("^%s*(.-)%s*$")
end

local function starts_with(s, prefix)
  return s:sub(1, #prefix) == prefix
end

local function parse_parameters(sql)
  local types = {}
  local cleaned = sql:gsub(":([%a_][%w_]*):(string|number|boolean)", function(name, typ)
    print("GOT NAME", name, "WITH TYPE", type)
    types[name] = typ
    return ":" .. name
  end)
  return cleaned, types
end

local function read_queries(filename)
  local queries = {}
  local f = io.open(filename, "r")
  if not f then error("Cannot open " .. filename) end

  local current = nil
  local sql_lines = {}
  local function flush()
    if current then
      local raw_sql = table.concat(sql_lines, "\n"):gsub("^%s*\n", "")       -- remove leading blank lines
      local cleaned_sql, param_types = parse_parameters(raw_sql)
      current.sql = cleaned_sql
      current.param_types = param_types
      table.insert(queries, current)
      current = nil
      sql_lines = {}
    end
  end

  for line in f:lines() do
    local trimmed = trim(line)
    if starts_with(trimmed, "-- :name") then
      flush()
      local name = trimmed:match("^%-%- %:name%s+(%S+)")
      if name then
        current = { name = name, type = "query_all" }         -- default
      else
        error("Invalid :name directive: " .. line)
      end
    elseif starts_with(trimmed, "-- :query_one") then
      if current then current.type = "query_one" end
    elseif starts_with(trimmed, "-- :query_all") then
      if current then current.type = "query_all" end
    elseif starts_with(trimmed, "-- :execute") then
      if current then current.type = "execute" end
    elseif starts_with(trimmed, "--") then
      -- ignore other comments
    else
      if current then
        -- collect SQL line (keep original whitespace for formatting)
        table.insert(sql_lines, line)
      end
    end
  end
  flush()
  f:close()
  return queries
end

local function escape_lua_string(str)
  -- Use long bracket string [[ ... ]] to avoid escaping quotes.
  -- But we must ensure no closing ]] inside. Simple heuristic: use [===[ ... ]===]
  -- For safety, replace any closing bracket sequence with a longer one.
  -- We'll just use multiline string with \n and assume no ]]== inside SQL.
  -- Simpler: use double quotes and escape backslashes and quotes.
  -- But long brackets are nicer.
  if str:find("]]") then
    -- Fallback to double quote escaping
    return '"' .. str:gsub('\\', '\\\\'):gsub('"', '\\"'):gsub('\n', '\\n') .. '"'
  else
    return "[[" .. str .. "]]"
  end
end

---@param str string SQL template with named placeholders like :name
local function SQL(str)
  local order = {}
  local seen = {}
  for name in str:gmatch(":(%w+)") do
    if not seen[name] then
      seen[name] = true
      order[#order + 1] = name
    end
  end

  local pos = {}
  for i, name in ipairs(order) do pos[name] = i end

  local sql = str:gsub(":(%w+)", function(name) return "?" .. pos[name] end)
  return sql, order
end

local function generate_module(queries)
  local lines = {}
  table.insert(lines, "-- Auto-generated by generate.lua")
  table.insert(lines, "-- Do not edit directly")
  table.insert(lines, "")
  table.insert(lines, [[
local function parse_args(args, order)
  local params = {}
  for i, name in ipairs(order) do params[i] = args[name] end
  return params
end
]])
  table.insert(lines, "")
  table.insert(lines, "return function(db)")
  table.insert(lines, "  local M = {}")
  table.insert(lines, "")

  for _, q in ipairs(queries) do
    local func_name = q.name
    local sql_str, order = SQL(escape_lua_string(q.sql))
    local method
    if q.type == "query_one" then
      method = "query_one"
    elseif q.type == "query_all" then
      method = "query_all"
    elseif q.type == "execute" then
      method = "execute"
    else
      error("Unknown type for " .. func_name)
    end

    pprint(q.param_types, order)
    table.insert(lines, string.format("  "))
    table.insert(lines, string.format("  function M.%s(args)", func_name))
    table.insert(lines, string.format("    local order = %s", table:to_string(order)))
    table.insert(lines, string.format("    return db:%s(%s, parse_args(args, order))", method, sql_str))
    table.insert(lines, "    end")
    table.insert(lines, "")
  end

  table.insert(lines, "  return M")
  table.insert(lines, "end")
  return table.concat(lines, "\n")
end

local input_file = "queries.sql"
local output_file = "sql.lua"


local queries = read_queries(input_file)
local lua_code = generate_module(queries)

local out = io.open(output_file, "w")
if not out then error("Cannot write " .. output_file) end
out:write(lua_code)
out:close()
print("Generated " .. output_file .. " with " .. #queries .. " queries.")
