require("utils")

local function trim(s)
  return s:match("^%s*(.-)%s*$")
end

local function starts_with(s, prefix)
  return s:sub(1, #prefix) == prefix
end

local function parse_parameters(sql)
  local types = {}
  local allowed_types = { string = true, number = true }

  local cleaned = sql:gsub(":([%a_][%w_]*):([%a_]+)", function(name, typ)
    if allowed_types[typ] then
      types[name] = typ
      return ":" .. name
    else
      return ":" .. name .. ":" .. typ
    end
  end)

  return cleaned, types
end

local function read_queries(filename)
  local queries = {}
  local f = io.open(filename, "r")
  if not f then error("Cannot open " .. filename) end

  local current = nil
  local sql_lines = {}
  local function flush()
    if current then
      local raw_sql = table.concat(sql_lines, "\n"):gsub("^%s*\n", "") -- remove leading blank lines
      local cleaned_sql, param_types = parse_parameters(raw_sql)
      current.sql = "\n" .. cleaned_sql .. "\n"
      current.param_types = param_types
      table.insert(queries, current)
      current = nil
      sql_lines = {}
    end
  end

  for line in f:lines() do
    local trimmed = trim(line)
    if line == "" then goto continue end
    if starts_with(trimmed, "-- :name") then
      flush()
      local name = trimmed:match("^%-%- %:name%s+(%S+)")
      if name then
        current = { name = name, type = "query_all" } -- default
      else
        error("Invalid :name directive: " .. line)
      end
    elseif starts_with(trimmed, "-- :query_one") then
      if current then current.type = "query_one" end
    elseif starts_with(trimmed, "-- :query_all") then
      if current then current.type = "query_all" end
    elseif starts_with(trimmed, "-- :execute") then
      if current then current.type = "execute" end
    elseif starts_with(trimmed, "-- :doc") then
      if current then current.doc = trimmed:match("^%-%- %:doc%s+(.*)") end
    elseif starts_with(trimmed, "--") then
      -- ignore other comments
    else
      if current then
        table.insert(sql_lines, line)
      end
    end
    ::continue::
  end
  flush()
  f:close()
  return queries
end

local function escape_lua_string(str)
  -- Use long bracket string [[ ... ]] to avoid escaping quotes.
  -- But we must ensure no closing ]] inside. Simple heuristic: use [===[ ... ]===]
  -- For safety, replace any closing bracket sequence with a longer one.
  -- We'll just use multiline string with \n and assume no ]]== inside SQL.
  -- Simpler: use double quotes and escape backslashes and quotes.
  -- But long brackets are nicer.
  if str:find("]]") then
    -- Fallback to double quote escaping
    return '"' ..
        str:gsub('\\', '\\\\'):gsub('"', '\\"'):gsub('\n', '\\n') .. '"'
  else
    return "[[" .. str .. "]]"
  end
end

---@param str string SQL template with named placeholders like :name
---@param dialect "sqlite"|"postgres"
local function SQL(str, dialect)
  local order = {}
  local seen = {}
  for name in str:gmatch(":(%w+)") do
    if not seen[name] then
      seen[name] = true
      order[#order + 1] = name
    end
  end

  local pos = {}
  for i, name in ipairs(order) do pos[name] = i end

  local placeholder
  if dialect == "postgres" then
    placeholder = "$"
  elseif dialect == "sqlite" then
    placeholder = "?"
  end

  local sql = str:gsub(":(%w+)", function(name)
    return placeholder .. pos[name]
  end)
  return sql, order
end

local function generate_module(queries, dialect)
  local lines = {}
  table.insert(lines, [[
-- Auto-generated by generate.lua
-- Do not edit directly

local function parse_args(args, order)
  local params = {}
  for i, name in ipairs(order) do params[i] = args[name] end
  return params
end

return function(db)
  local M = {}
]])

  for _, q in ipairs(queries) do
    local func_name = q.name
    local sql_str, order = SQL(escape_lua_string(q.sql), dialect)
    local method
    if q.type == "query_one" then
      method = "query_one"
    elseif q.type == "query_all" then
      method = "query_all"
    elseif q.type == "execute" then
      method = "execute"
    else
      error("Unknown type for " .. func_name)
    end

    if q.doc then
      table.insert(lines, string.format("  --- %s", q.doc))
    end
    if #order == 0 then
      table.insert(lines, string.format("  function M.%s()", func_name))
      table.insert(lines, string.format("    local ok, result = pcall(db.%s, db, %s)", method, sql_str))
      table.insert(lines, string.format("    return ok, result"))
    else
      local parts = {}
      for _, param_name in ipairs(order) do
        local typ = q.param_types[param_name]
        if typ then
          parts[#parts + 1] = param_name .. ": " .. typ
        end
      end
      table.insert(lines, string.format("  ---@param args { %s }", table.concat(parts, ", ")))
      table.insert(lines, string.format("  function M.%s(args)", func_name))
      table.insert(lines, string.format("    local order = %s", table:to_string(order)))
      table.insert(lines, string.format("    local ok, result = pcall(db.%s, db, %s, parse_args(args, order))", method, sql_str))
      table.insert(lines, string.format("    return ok, result"))
    end
    table.insert(lines, "  end")
    table.insert(lines, "")
  end

  table.insert(lines, [[
  return M
end
]])
  return table.concat(lines, "\n")
end

---@param input_file string
---@param dialect "sqlite"|"postgres"
return function(input_file, dialect)
  local output_file = input_file:gsub("%.sql$", "") .. ".lua"

  local queries = read_queries(input_file)
  local lua_code = generate_module(queries, dialect)

  local out = io.open(output_file, "w")
  if not out then
    error("Cannot write " .. output_file)
  end
  out:write(lua_code)
  out:close()
  print("Generated " .. output_file .. " with " .. #queries .. " queries.")
end
