-- Auto-generated by generate.lua
-- Do not edit directly

local function parse_args(args, order)
  local params = {}
  for i, name in ipairs(order) do params[i] = args[name] end
  return params
end


return function(db)
  local M = {}

  
  function M.get_user(args)
    local order = { 'id', 'number' }
    return db:query_all([[SELECT * FROM users WHERE id = ?1?2
]], parse_args(args, order))
    end

  
  function M.update_user_name(args)
    local order = { 'name', 'string', 'id', 'number' }
    return db:execute([[UPDATE users SET name = ?1?2 WHERE id = ?3?4
]], parse_args(args, order))
    end

  
  function M.list_active_users(args)
    local order = {  }
    return db:query_all([[SELECT * FROM users WHERE active = 1
]], parse_args(args, order))
    end

  
  function M.create_guestbook_table(args)
    local order = {  }
    return db:execute([[CREATE TABLE guestbook (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(30),
  message VARCHAR(200),
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
]], parse_args(args, order))
    end

  
  function M.drop_guestbook_table(args)
    local order = {  }
    return db:execute([[DROP TABLE IF EXISTS guestbook;
]], parse_args(args, order))
    end

  
  function M.save_message(args)
    local order = { 'name', 'string', 'message' }
    return db:execute([[INSERT INTO guestbook
(name, message)
VALUES (?1?2, ?3?2);
]], parse_args(args, order))
    end

  
  function M.get_messages(args)
    local order = {  }
    return db:query_all([[SELECT * FROM guestbook;
]], parse_args(args, order))
    end

  
  function M.get_messages_by_name(args)
    local order = { 'name', 'string' }
    return db:query_all([[SELECT id, message, timestamp
FROM guestbook
WHERE name = ?1?2
ORDER BY timestamp DESC;]], parse_args(args, order))
    end

  return M
end